/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import datos.CaracteristicaDAO;
import datos.InscripcionDAO;
import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.Evento;
import negocio.GestorEvento;
import negocio.GestorInscripcion;
import negocio.Inscripcion;
import util.CaException;

/**
 *
 * @author PC-Lirol
 */
public class IncribirAso extends javax.swing.JFrame {

    /**
     * Creates new form menuPersona
     */
    Inscripcion insReal;
    boolean asiste = false;

    public IncribirAso() {

        super("Inscribirse a un evento");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idEvento = new javax.swing.JTextField();
        cedula = new javax.swing.JTextField();
        inscribirse = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tipoID1 = new javax.swing.JComboBox<>();
        asis = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idInsc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Identificacion del evento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 140, 20));

        jLabel2.setText("Identificion del Asociado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, 20));

        jLabel3.setText("Asiste al evento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 20));
        getContentPane().add(idEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 200, -1));
        getContentPane().add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 110, -1));

        inscribirse.setText("Inscribirse");
        inscribirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscribirseActionPerformed(evt);
            }
        });
        getContentPane().add(inscribirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 90, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 30, 10));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 70, -1));

        tipoID1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "PA", "CA" }));
        getContentPane().add(tipoID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        asis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no" }));
        getContentPane().add(asis, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Hacer Inscripcion");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel6.setText("Identificador Inscripcion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, 20));
        getContentPane().add(idInsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inscribirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscribirseActionPerformed

        GestorInscripcion gestor = new GestorInscripcion();
        GestorEvento gestorE = new GestorEvento();
        CaracteristicaDAO caracDao = gestorE.getCaracteristicaDAO();
        InscripcionDAO inscripcionDAO = gestor.getInscripcionDAO();
        insReal = inscripcionDAO.getIns();
        try {
           
            caracDao.getCar().setK_code(Integer.parseInt(idEvento.getText()));
            caracDao.buscarCaracteristica();
            gestorE.getEventoDAO().getEv().setK_code(Integer.parseInt(idEvento.getText()));
            gestorE.getEventoDAO().buscarEvento();
           
            int cupos = gestorE.buscarCupo();
            boolean inscrip = gestorE.getEventoDAO().getEv().isO_tieneins();
           
            
            if (cupos > 0 && inscrip) {
                
                insReal.setK_ins(Integer.parseInt(idInsc.getText()));
                if (caracDao.getCar().getO_tipopag().equals("V")) {
                    insReal.setI_estadoi("CO");
                } else {
                    insReal.setI_estadoi("ES");
                }

                if (asis.getSelectedIndex() == 0) {
                    asiste = true;
                } else {
                    asiste = false;
                }

                insReal.setO_asiste(asiste);
                insReal.setK_tipo(tipoID1.getItemAt(tipoID1.getSelectedIndex()));
                insReal.setK_code(Integer.parseInt(idEvento.getText()));
                insReal.setK_num(Integer.parseInt(cedula.getText()));
                
                if (asiste && caracDao.getCar().getK_codev() != -1) {//Hay que actualizar el valor de la inscripcion
                    insReal.setV_ins(caracDao.getCar().getV_copago());
                }else{
                    insReal.setV_ins(0);
                }
                
                inscripcionDAO.setIns(insReal);
                if (asiste) {
                    gestorE.getEventoDAO().actualizarCupo();
                }
                gestor.setInscripcionDAO(inscripcionDAO);
                inscripcionDAO.incluirInscripcion();
                JOptionPane.showMessageDialog(null, "Se ha realizado la inscripcion con numero: " + Integer.parseInt(idInsc.getText()));
                
            } else {
                JOptionPane.showMessageDialog(null, "El no presenta cupo o opcion de inscripcion");
            }
        } catch (CaException ex) {
            JOptionPane.showMessageDialog(null, "Inscripcion invalida, verifique los datos", "ERROR", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_inscribirseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VistaAsociado m = new VistaAsociado();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncribirAso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncribirAso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncribirAso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncribirAso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IncribirAso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> asis;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField idEvento;
    private javax.swing.JTextField idInsc;
    private javax.swing.JButton inscribirse;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> tipoID1;
    // End of variables declaration//GEN-END:variables
}
