/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 03-mar.-2020 6:22:56 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS Asociado CASCADE
;

DROP TABLE IF EXISTS Caracteristica CASCADE
;

DROP TABLE IF EXISTS DetalleInscripcion CASCADE
;

DROP TABLE IF EXISTS Evento CASCADE
;

DROP TABLE IF EXISTS Familiar CASCADE
;

DROP TABLE IF EXISTS Inscripcion CASCADE
;

DROP TABLE IF EXISTS PagoI CASCADE
;

DROP TABLE IF EXISTS PagoP CASCADE
;

DROP TABLE IF EXISTS Proveedor CASCADE
;

DROP TABLE IF EXISTS Tipo CASCADE
;

DROP TABLE IF EXISTS Usuario CASCADE
;

/* Create Tables */

CREATE TABLE Asociado
(
	o_tel numeric(10) NOT NULL,	-- Telefono del asociado
	f_afiliacion date NOT NULL,	-- Fecha de afiliacion del asociado
	v_sueldo numeric(10,2) NOT NULL,	-- Sueldo del asociado
	f_nto date NOT NULL,	-- Fecha de nacimiento del asociado
	k_tipo varchar(2) NOT NULL,	-- Tipo de identificacion del asociado
	k_num integer NOT NULL,	-- Numero de identificacion del asociado
	n_nombre1 varchar(20) NOT NULL,	-- Primer nombre del asociado 
	n_nombre2 varchar(20) NOT NULL,	-- Segundo nombre del asociado 
	n_ap1 varchar(20) NOT NULL,	-- Primer apellido del asociado
	n_ap2 varchar(20) NOT NULL,	-- Segundo apellido del asociado
	o_genero varchar(1) NOT NULL,	-- Genero del asociado
	n_calle varchar(15) NOT NULL,	-- Calle de la direccion del asociado
	n_num varchar(15) NOT NULL,	-- Numero de la direccion del asociado
	n_barrio varchar(20) NOT NULL,	-- Barrio de la direccion del asociado
	n_ciudad varchar(15) NOT NULL,	-- Ciudad de la direccion del asociado
	n_complemento varchar(20) NOT NULL,	-- Complemento de la direccion del asociado
	o_email varchar(35) NULL	-- Email del asociado
)
;

CREATE TABLE Caracteristica
(
	k_codev integer NOT NULL,	-- Llave primaria que hace referencia al codigo del evento
	p_subsidio numeric(5,2) NOT NULL,	-- Subsidio que va a tener el evento
	o_tipopag varchar(1) NOT NULL,	-- Tipo de pago del evento
	q_cuotasmax integer NOT NULL,	-- Cuotas maximas del pago 
	v_copago numeric(9,2) NOT NULL	-- Valor del copago del evento
)
;

CREATE TABLE DetalleInscripcion
(
	k_iddi integer NOT NULL,	-- Llave primaria del detalle de inscripcion
	k_ins integer NOT NULL,	-- Llave primaria y foranea de inscripcion
	k_numidf integer NOT NULL,	-- Llave foranea Familiar
	k_tipoidf varchar(2) NOT NULL	-- Llave foranea Familiar
)
;

CREATE TABLE Evento
(
	i_estado varchar(1) NOT NULL,	-- Estado en el que se encuentra el evento
	q_cupo integer NOT NULL,	-- Cupo del evento
	v_total numeric(13,2) NOT NULL,	-- Valor total del evento
	k_code integer NOT NULL,	-- Llave primaria correspondiente a la clave distintiva del evento
	o_tieneins boolean NOT NULL,	-- Para saber si tiene o no inscripcion
	f_cancelmax date NOT NULL,	-- Fecha maxima de cancelacion del evento
	n_lugar varchar(20) NOT NULL,	-- Nombre del lugar donde se realizara el evento
	o_descripcion varchar(200) NOT NULL,	-- Descripcion del evento
	n_nombrev varchar(30) NOT NULL,	-- Nombre del  evento
	f_ini date NOT NULL,	-- Fecha inicio del evento
	f_fin date NOT NULL,	-- Fecha finalizacion del evento
	f_maxins date NOT NULL,	-- Fecha maxima de inscripcion del evento
	o_observ varchar(50) NOT NULL,	-- Observaciones sobre el evento
	q_cupodisp integer NOT NULL,	-- Cupos disponibles del evento
	f_cierre date NOT NULL,	-- Fecha de cierre total del evento
	o_sobrecupo boolean NOT NULL,	-- Saber si hay o no sobrecupo del evento
	k_codev integer NOT NULL,	-- Llave foranea de caracteristicas del evento
	k_idt integer NOT NULL	-- Llave foranea tipo evento
)
;

CREATE TABLE Familiar
(
	f_ntof date NOT NULL,	-- Fecha de nacimiento del familiar del asociado
	k_numidf integer NOT NULL,	-- Numero de identificacion del familiar del asociado
	k_tipoidf varchar(2) NOT NULL,	-- Tipo de identificacion del familiar del asociado
	n_nombre1f varchar(20) NOT NULL,	-- Primer nombre del familiar del asociado
	n_nombre2f varchar(20) NOT NULL,	-- Segundo nombre del familiar del asociado
	n_ap1f varchar(20) NOT NULL,	-- Primer apellido del familiar del asociado
	n_ap2f varchar(20) NOT NULL,	-- Segundo apellido del familiar del asociado
	o_parentesco varchar(20) NOT NULL,	-- Parentesco del familiar del asociado
	k_tipo varchar(2) NOT NULL,	-- Llave foranea del asociado
	k_num integer NOT NULL	-- Llave foranea del asociado
)
;

CREATE TABLE Inscripcion
(
	k_ins integer NOT NULL,	-- Llave primaria de las inscripciones
	i_estadoi varchar(2) NOT NULL,	-- Estado en el que se encuentra la inscripcion
	v_ins numeric(9,2) NOT NULL,	-- Valor de la inscripcion
	f_inscrip date NOT NULL,	-- Fecha de inscripcion al evento
	o_asiste boolean NOT NULL,	-- Atributo de la relacion
	k_tipo varchar(2) NOT NULL,	-- Llave foranea de asociado
	k_num integer NOT NULL,	-- Llave foranea de asociado
	k_code integer NOT NULL	-- Llave foranea evento
)
;

CREATE TABLE PagoI
(
	k_idpi integer NOT NULL,	-- Llave primaria del pago de la inscripcion
	f_pagopi date NOT NULL,	-- Fecha de pago de la insripcion
	o_fpagoi varchar(2) NOT NULL,	-- Forma de pago de la inscripcion
	v_inspi numeric(9,2) NOT NULL,	-- Valor del pago de la inscripcion
	k_ins integer NOT NULL	-- Llave foranea inscripcion
)
;

CREATE TABLE PagoP
(
	k_idpp integer NOT NULL,	-- Llave primaria del pago al proveedor
	f_pagop date NOT NULL,	-- Fecha de pago al proveedor
	o_formapp varchar(2) NOT NULL,	-- Forma de pago al proveedor
	k_idp integer NOT NULL	-- Llave foranea proveedor
)
;

CREATE TABLE Proveedor
(
	k_idp integer NOT NULL,	-- Llave primaria del proveedor
	n_nombrep varchar(25) NOT NULL,	-- Nombre del proveedor
	o_telp integer NOT NULL,	-- Telefono del proveedor
	n_callep varchar(50) NOT NULL,	-- Calle de la direccion del proveedor
	n_nump varchar(20) NOT NULL,	-- Numero de la direccion del proveedor
	n_barriop varchar(20) NOT NULL,	-- Barrio de la direccion del proveedor
	n_ciudadp varchar(20) NOT NULL,	-- Ciudad de la direccion del proveedor
	n_compp varchar(20) NOT NULL,	-- Complemento de la direccion del proveedor
	k_code integer NOT NULL	-- Llave foranea del evento
)
;

CREATE TABLE Tipo
(
	k_idt integer NOT NULL,	-- Llave primaria del tipo de evento
	n_nombre varchar(20) NOT NULL	-- Nombre del tipo de evento 
)
;

CREATE TABLE Usuario
(
	k_idu integer NOT NULL,	-- Llave primaria del usuario
	o_rol varchar(1) NOT NULL,	-- Rol del usuario
	o_pass varchar(20) NOT NULL	-- Contraseña del usuario
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Asociado ADD CONSTRAINT PK_Asociado
	PRIMARY KEY (k_tipo,k_num)
;

ALTER TABLE Asociado ADD CONSTRAINT CK_otel CHECK (o_tel>0)
;

ALTER TABLE Asociado ADD CONSTRAINT CK_vsueldo CHECK (v_sueldo>0)
;

ALTER TABLE Asociado ADD CONSTRAINT CK_ktipo CHECK (k_tipo IN ('CC','PA','CE'))
;

ALTER TABLE Asociado ADD CONSTRAINT CK_knum CHECK (k_num>0)
;

ALTER TABLE Asociado ADD CONSTRAINT CK_fafiliacion CHECK (f_afiliacion <= CURRENT_DATE )
;

ALTER TABLE Asociado ADD CONSTRAINT CK_fnto CHECK (f_nto < CURRENT_DATE )
;

ALTER TABLE Asociado ADD CONSTRAINT CK_ogenero CHECK (o_genero in ('m','f','o'))
;

ALTER TABLE Caracteristica ADD CONSTRAINT PK_Caracteristica
	PRIMARY KEY (k_codev)
;

ALTER TABLE Caracteristica ADD CONSTRAINT CK_kcodev CHECK (k_codev>0)
;

ALTER TABLE Caracteristica ADD CONSTRAINT CK_psubsidio CHECK (p_subsidio <=100 and p_subsidio>=0)
;

ALTER TABLE Caracteristica ADD CONSTRAINT CK_otipopag CHECK (o_tipopag IN ('V','N'))
;

ALTER TABLE Caracteristica ADD CONSTRAINT CK_qcuotasmax CHECK (q_cuotasmax>0)
;

ALTER TABLE Caracteristica ADD CONSTRAINT CK_vcopago CHECK (v_copago >= 0)
;

ALTER TABLE DetalleInscripcion ADD CONSTRAINT PK_DetalleInscripcion
	PRIMARY KEY (k_iddi,k_ins)
;

ALTER TABLE DetalleInscripcion ADD CONSTRAINT CK_kiddi CHECK (k_iddi > 0)
;

CREATE INDEX IXFK_DetalleInscripcion_Familiar ON DetalleInscripcion (k_numidf ASC,k_tipoidf ASC)
;

CREATE INDEX IXFK_DetalleInscripcion_Inscripcion ON DetalleInscripcion (k_ins ASC)
;

ALTER TABLE Evento ADD CONSTRAINT PK_Evento
	PRIMARY KEY (k_code)
;

ALTER TABLE Evento ADD CONSTRAINT CK_iestado CHECK (i_estado IN ('A','C','L'))
;

ALTER TABLE Evento ADD CONSTRAINT CK_qcupo CHECK (q_cupo > 0)
;

ALTER TABLE Evento ADD CONSTRAINT CK_vtotal CHECK (v_total > 0)
;

ALTER TABLE Evento ADD CONSTRAINT CK_kcode CHECK (k_code > 0 )
;

ALTER TABLE Evento ADD CONSTRAINT CK_fcancelmax CHECK (f_cancelmax < f_ini )
;

ALTER TABLE Evento ADD CONSTRAINT CK_fini CHECK (f_ini > CURRENT_DATE )
;

ALTER TABLE Evento ADD CONSTRAINT CK_ffin CHECK (f_fin>f_ini )
;

ALTER TABLE Evento ADD CONSTRAINT CK_fmaxins CHECK (f_maxins < f_ini )
;

ALTER TABLE Evento ADD CONSTRAINT CK_qcupodisp CHECK (q_cupodisp<=q_cupo)
;

ALTER TABLE Evento ADD CONSTRAINT CK_fcierre CHECK (f_cierre >= f_fin)
;

CREATE INDEX IXFK_Evento_Caracteristica ON Evento (k_codev ASC)
;

CREATE INDEX IXFK_Evento_Tipo ON Evento (k_idt ASC)
;

ALTER TABLE Familiar ADD CONSTRAINT PK_Familiar
	PRIMARY KEY (k_numidf,k_tipoidf)
;

ALTER TABLE Familiar ADD CONSTRAINT CK_fntof CHECK (f_ntof < CURRENT_DATE )
;

ALTER TABLE Familiar ADD CONSTRAINT CK_knumidf CHECK (k_numidf>0)
;

ALTER TABLE Familiar ADD CONSTRAINT CK_ktipoidf CHECK (k_tipoidf IN ('CC','PA','CE'))
;

ALTER TABLE Familiar ADD CONSTRAINT CK_oparentesco CHECK (o_parentesco in ('padre','madre','conyugue','tio','primo','sobrino','hermano','primo','hijo','abuelo','nieto','bisabuelo'))
;

CREATE INDEX IXFK_Familiar_Asociado ON Familiar (k_tipo ASC,k_num ASC)
;

ALTER TABLE Inscripcion ADD CONSTRAINT PK_Inscripcion
	PRIMARY KEY (k_ins)
;

ALTER TABLE Inscripcion ADD CONSTRAINT CK_kins CHECK (k_ins>0)
;

ALTER TABLE Inscripcion ADD CONSTRAINT CK_iestadoi CHECK (i_estadoi IN ('ES','CO','CA'))
;

ALTER TABLE Inscripcion ADD CONSTRAINT CK_vins CHECK (v_ins>=0)
;

CREATE INDEX IXFK_Inscripcion_Asociado ON Inscripcion (k_tipo ASC,k_num ASC)
;

CREATE INDEX IXFK_Inscripcion_Evento ON Inscripcion (k_code ASC)
;

ALTER TABLE PagoI ADD CONSTRAINT PK_PagoI
	PRIMARY KEY (k_idpi)
;

ALTER TABLE PagoI ADD CONSTRAINT CK_kidpi CHECK (k_idpi > 0)
;

ALTER TABLE PagoI ADD CONSTRAINT CK_ofpagoi CHECK (o_fpagoi IN ('CH','EF','TC','TD'))
;

ALTER TABLE PagoI ADD CONSTRAINT CK_vinspi CHECK (v_inspi > 0)
;

CREATE INDEX IXFK_PagoI_Inscripcion ON PagoI (k_ins ASC)
;

ALTER TABLE PagoP ADD CONSTRAINT PK_PagoP
	PRIMARY KEY (k_idpp)
;

ALTER TABLE PagoP ADD CONSTRAINT CK_kidpp CHECK (k_idpp > 0)
;

ALTER TABLE PagoP ADD CONSTRAINT CK_oformapp CHECK (o_formapp IN ('CH','EF','TC','TD'))
;

CREATE INDEX IXFK_PagoP_Proveedor ON PagoP (k_idp ASC)
;

ALTER TABLE Proveedor ADD CONSTRAINT PK_Proveedor
	PRIMARY KEY (k_idp)
;

ALTER TABLE Proveedor ADD CONSTRAINT CK_kidp CHECK (k_idp > 0)
;

ALTER TABLE Proveedor ADD CONSTRAINT CK_otelp CHECK (o_telp > 0)
;

CREATE INDEX IXFK_Proveedor_Evento ON Proveedor (k_code ASC)
;

ALTER TABLE Tipo ADD CONSTRAINT PK_Tipo
	PRIMARY KEY (k_idt)
;

ALTER TABLE Tipo ADD CONSTRAINT CK_kidt CHECK (k_idt>0)
;

ALTER TABLE Usuario ADD CONSTRAINT PK_Usuario
	PRIMARY KEY (k_idu)
;

ALTER TABLE Usuario ADD CONSTRAINT CK_kidu CHECK (k_idu > 0)
;

ALTER TABLE Usuario ADD CONSTRAINT CK_orol CHECK (o_rol IN ('F','A'))
;

/* Create Foreign Key Constraints */

ALTER TABLE DetalleInscripcion ADD CONSTRAINT FK_DetalleInscripcion_Familiar
	FOREIGN KEY (k_numidf,k_tipoidf) REFERENCES Familiar (k_numidf,k_tipoidf) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE DetalleInscripcion ADD CONSTRAINT FK_DetalleInscripcion_Inscripcion
	FOREIGN KEY (k_ins) REFERENCES Inscripcion (k_ins) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Evento ADD CONSTRAINT FK_Evento_Caracteristica
	FOREIGN KEY (k_codev) REFERENCES Caracteristica (k_codev) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Evento ADD CONSTRAINT FK_Evento_Tipo
	FOREIGN KEY (k_idt) REFERENCES Tipo (k_idt) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Familiar ADD CONSTRAINT FK_Familiar_Asociado
	FOREIGN KEY (k_tipo,k_num) REFERENCES Asociado (k_tipo,k_num) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Inscripcion ADD CONSTRAINT FK_Inscripcion_Asociado
	FOREIGN KEY (k_tipo,k_num) REFERENCES Asociado (k_tipo,k_num) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Inscripcion ADD CONSTRAINT FK_Inscripcion_Evento
	FOREIGN KEY (k_code) REFERENCES Evento (k_code) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE PagoI ADD CONSTRAINT FK_PagoI_Inscripcion
	FOREIGN KEY (k_ins) REFERENCES Inscripcion (k_ins) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE PagoP ADD CONSTRAINT FK_PagoP_Proveedor
	FOREIGN KEY (k_idp) REFERENCES Proveedor (k_idp) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Proveedor ADD CONSTRAINT FK_Proveedor_Evento
	FOREIGN KEY (k_code) REFERENCES Evento (k_code) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE Asociado
	IS 'Entidad que define a un asociado con sus respectivos datos'
;

COMMENT ON COLUMN Asociado.o_tel
	IS 'Telefono del asociado'
;

COMMENT ON COLUMN Asociado.f_afiliacion
	IS 'Fecha de afiliacion del asociado'
;

COMMENT ON COLUMN Asociado.v_sueldo
	IS 'Sueldo del asociado'
;

COMMENT ON COLUMN Asociado.f_nto
	IS 'Fecha de nacimiento del asociado'
;

COMMENT ON COLUMN Asociado.k_tipo
	IS 'Tipo de identificacion del asociado'
;

COMMENT ON COLUMN Asociado.k_num
	IS 'Numero de identificacion del asociado'
;

COMMENT ON COLUMN Asociado.n_nombre1
	IS 'Primer nombre del asociado '
;

COMMENT ON COLUMN Asociado.n_nombre2
	IS 'Segundo nombre del asociado '
;

COMMENT ON COLUMN Asociado.n_ap1
	IS 'Primer apellido del asociado'
;

COMMENT ON COLUMN Asociado.n_ap2
	IS 'Segundo apellido del asociado'
;

COMMENT ON COLUMN Asociado.o_genero
	IS 'Genero del asociado'
;

COMMENT ON COLUMN Asociado.n_calle
	IS 'Calle de la direccion del asociado'
;

COMMENT ON COLUMN Asociado.n_num
	IS 'Numero de la direccion del asociado'
;

COMMENT ON COLUMN Asociado.n_barrio
	IS 'Barrio de la direccion del asociado'
;

COMMENT ON COLUMN Asociado.n_ciudad
	IS 'Ciudad de la direccion del asociado'
;

COMMENT ON COLUMN Asociado.n_complemento
	IS 'Complemento de la direccion del asociado'
;

COMMENT ON COLUMN Asociado.o_email
	IS 'Email del asociado'
;

COMMENT ON TABLE Caracteristica
	IS 'Entidad de las caracteristicas del evento a realizar'
;

COMMENT ON COLUMN Caracteristica.k_codev
	IS 'Llave primaria que hace referencia al codigo del evento'
;

COMMENT ON COLUMN Caracteristica.p_subsidio
	IS 'Subsidio que va a tener el evento'
;

COMMENT ON COLUMN Caracteristica.o_tipopag
	IS 'Tipo de pago del evento'
;

COMMENT ON COLUMN Caracteristica.q_cuotasmax
	IS 'Cuotas maximas del pago '
;

COMMENT ON COLUMN Caracteristica.v_copago
	IS 'Valor del copago del evento'
;

COMMENT ON TABLE DetalleInscripcion
	IS 'Entidad del detalle de inscripcion'
;

COMMENT ON COLUMN DetalleInscripcion.k_iddi
	IS 'Llave primaria del detalle de inscripcion'
;

COMMENT ON COLUMN DetalleInscripcion.k_ins
	IS 'Llave primaria y foranea de inscripcion'
;

COMMENT ON COLUMN DetalleInscripcion.k_numidf
	IS 'Llave foranea Familiar'
;

COMMENT ON COLUMN DetalleInscripcion.k_tipoidf
	IS 'Llave foranea Familiar'
;

COMMENT ON TABLE Evento
	IS 'Entidad correspondiente al evento con sus respectivos datos'
;

COMMENT ON COLUMN Evento.i_estado
	IS 'Estado en el que se encuentra el evento'
;

COMMENT ON COLUMN Evento.q_cupo
	IS 'Cupo del evento'
;

COMMENT ON COLUMN Evento.v_total
	IS 'Valor total del evento'
;

COMMENT ON COLUMN Evento.k_code
	IS 'Llave primaria correspondiente a la clave distintiva del evento'
;

COMMENT ON COLUMN Evento.o_tieneins
	IS 'Para saber si tiene o no inscripcion'
;

COMMENT ON COLUMN Evento.f_cancelmax
	IS 'Fecha maxima de cancelacion del evento'
;

COMMENT ON COLUMN Evento.n_lugar
	IS 'Nombre del lugar donde se realizara el evento'
;

COMMENT ON COLUMN Evento.o_descripcion
	IS 'Descripcion del evento'
;

COMMENT ON COLUMN Evento.n_nombrev
	IS 'Nombre del  evento'
;

COMMENT ON COLUMN Evento.f_ini
	IS 'Fecha inicio del evento'
;

COMMENT ON COLUMN Evento.f_fin
	IS 'Fecha finalizacion del evento'
;

COMMENT ON COLUMN Evento.f_maxins
	IS 'Fecha maxima de inscripcion del evento'
;

COMMENT ON COLUMN Evento.o_observ
	IS 'Observaciones sobre el evento'
;

COMMENT ON COLUMN Evento.q_cupodisp
	IS 'Cupos disponibles del evento'
;

COMMENT ON COLUMN Evento.f_cierre
	IS 'Fecha de cierre total del evento'
;

COMMENT ON COLUMN Evento.o_sobrecupo
	IS 'Saber si hay o no sobrecupo del evento'
;

COMMENT ON COLUMN Evento.k_codev
	IS 'Llave foranea de caracteristicas del evento'
;

COMMENT ON COLUMN Evento.k_idt
	IS 'Llave foranea tipo evento'
;

COMMENT ON TABLE Familiar
	IS 'Entidad del familiar del asociado'
;

COMMENT ON COLUMN Familiar.f_ntof
	IS 'Fecha de nacimiento del familiar del asociado'
;

COMMENT ON COLUMN Familiar.k_numidf
	IS 'Numero de identificacion del familiar del asociado'
;

COMMENT ON COLUMN Familiar.k_tipoidf
	IS 'Tipo de identificacion del familiar del asociado'
;

COMMENT ON COLUMN Familiar.n_nombre1f
	IS 'Primer nombre del familiar del asociado'
;

COMMENT ON COLUMN Familiar.n_nombre2f
	IS 'Segundo nombre del familiar del asociado'
;

COMMENT ON COLUMN Familiar.n_ap1f
	IS 'Primer apellido del familiar del asociado'
;

COMMENT ON COLUMN Familiar.n_ap2f
	IS 'Segundo apellido del familiar del asociado'
;

COMMENT ON COLUMN Familiar.o_parentesco
	IS 'Parentesco del familiar del asociado'
;

COMMENT ON COLUMN Familiar.k_tipo
	IS 'Llave foranea del asociado'
;

COMMENT ON COLUMN Familiar.k_num
	IS 'Llave foranea del asociado'
;

COMMENT ON TABLE Inscripcion
	IS 'Entidad que corresponde a la inscripcion del evento'
;

COMMENT ON COLUMN Inscripcion.k_ins
	IS 'Llave primaria de las inscripciones'
;

COMMENT ON COLUMN Inscripcion.i_estadoi
	IS 'Estado en el que se encuentra la inscripcion'
;

COMMENT ON COLUMN Inscripcion.v_ins
	IS 'Valor de la inscripcion'
;

COMMENT ON COLUMN Inscripcion.f_inscrip
	IS 'Fecha de inscripcion al evento'
;

COMMENT ON COLUMN Inscripcion.o_asiste
	IS 'Atributo de la relacion'
;

COMMENT ON COLUMN Inscripcion.k_tipo
	IS 'Llave foranea de asociado'
;

COMMENT ON COLUMN Inscripcion.k_num
	IS 'Llave foranea de asociado'
;

COMMENT ON COLUMN Inscripcion.k_code
	IS 'Llave foranea evento'
;

COMMENT ON TABLE PagoI
	IS 'Entidad del pago de las inscripciones'
;

COMMENT ON COLUMN PagoI.k_idpi
	IS 'Llave primaria del pago de la inscripcion'
;

COMMENT ON COLUMN PagoI.f_pagopi
	IS 'Fecha de pago de la insripcion'
;

COMMENT ON COLUMN PagoI.o_fpagoi
	IS 'Forma de pago de la inscripcion'
;

COMMENT ON COLUMN PagoI.v_inspi
	IS 'Valor del pago de la inscripcion'
;

COMMENT ON COLUMN PagoI.k_ins
	IS 'Llave foranea inscripcion'
;

COMMENT ON TABLE PagoP
	IS 'Entidad del pago al proveedor'
;

COMMENT ON COLUMN PagoP.k_idpp
	IS 'Llave primaria del pago al proveedor'
;

COMMENT ON COLUMN PagoP.f_pagop
	IS 'Fecha de pago al proveedor'
;

COMMENT ON COLUMN PagoP.o_formapp
	IS 'Forma de pago al proveedor'
;

COMMENT ON COLUMN PagoP.k_idp
	IS 'Llave foranea proveedor'
;

COMMENT ON TABLE Proveedor
	IS 'Entidad del proveedor del evento'
;

COMMENT ON COLUMN Proveedor.k_idp
	IS 'Llave primaria del proveedor'
;

COMMENT ON COLUMN Proveedor.n_nombrep
	IS 'Nombre del proveedor'
;

COMMENT ON COLUMN Proveedor.o_telp
	IS 'Telefono del proveedor'
;

COMMENT ON COLUMN Proveedor.n_callep
	IS 'Calle de la direccion del proveedor'
;

COMMENT ON COLUMN Proveedor.n_nump
	IS 'Numero de la direccion del proveedor'
;

COMMENT ON COLUMN Proveedor.n_barriop
	IS 'Barrio de la direccion del proveedor'
;

COMMENT ON COLUMN Proveedor.n_ciudadp
	IS 'Ciudad de la direccion del proveedor'
;

COMMENT ON COLUMN Proveedor.n_compp
	IS 'Complemento de la direccion del proveedor'
;

COMMENT ON COLUMN Proveedor.k_code
	IS 'Llave foranea del evento'
;

COMMENT ON TABLE Tipo
	IS 'Entidad que tiene la informacion del tipo de evento que se va a realizar'
;

COMMENT ON COLUMN Tipo.k_idt
	IS 'Llave primaria del tipo de evento'
;

COMMENT ON COLUMN Tipo.n_nombre
	IS 'Nombre del tipo de evento '
;

COMMENT ON TABLE Usuario
	IS 'Entidad del usuario del gestor'
;

COMMENT ON COLUMN Usuario.k_idu
	IS 'Llave primaria del usuario'
;

COMMENT ON COLUMN Usuario.o_rol
	IS 'Rol del usuario'
;

COMMENT ON COLUMN Usuario.o_pass
	IS 'Contraseña del usuario'
;
